name: daily-cron
on:
  schedule:
    - cron: '5,10,15,25,35,45,55 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --url 'https://github.com'
