name: daily-cron
on:
  schedule:
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55  * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --url 'https://awesomely.vercel.app/api/hello'
