name: daily-cron
on:
  schedule:
    - cron: '* 10,20,30,40,50 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://awesomely.vercel.app/api/hello'
